
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo7-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Nevod-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 32167dima
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: demo7-db
    environment:
      POSTGRES_DB: Nevod-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 32167dima
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
